import parse from 'date-fns/parse';
import getHours from 'date-fns/getHours';
import getMinutes from 'date-fns/getMinutes';
import timeZoneData from './timezones.json';

const emptySlot = day => ({
  day,
  from: '',
  to: '',
  valid: false,
  openAllDay: false,
  hasLunchBreak: false,
  lunchFrom: '',
  lunchTo: '',
});

export const defaultTimeSlot = [0, 1, 2, 3, 4, 5, 6].map(emptySlot);

export const generateTimeSlots = (step = 15) => {
  /* 
    Generates a list of time strings from 12:00 AM to next 24 hours. Each new string
     will be generated by adding `step` minutes to the previous one.
    The list is generated by starting with a random day and adding step minutes till end of the same day.
    Always includes 11:59 PM as the final slot to complete the day.
  */
  const date = new Date(1970, 1, 1);
  const slots = [];
  while (date.getDate() === 1) {
    slots.push(
      date.toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
        hour12: true,
      })
    );
    date.setMinutes(date.getMinutes() + step);
  }

  // Always add 11:59 PM as the final slot if it's not already included
  const lastSlot = '11:59 PM';
  if (!slots.includes(lastSlot)) {
    slots.push(lastSlot);
  }

  return slots;
};

export const getTime = (hour, minute) => {
  const merdian = hour > 11 ? 'PM' : 'AM';
  const modHour = hour > 12 ? hour % 12 : hour || 12;
  const parsedHour = modHour < 10 ? `0${modHour}` : modHour;
  const parsedMinute = minute < 10 ? `0${minute}` : minute;
  return `${parsedHour}:${parsedMinute} ${merdian}`;
};

export const timeSlotParse = timeSlots => {
  return timeSlots.map(slot => {
    const {
      day_of_week: day,
      open_hour: openHour,
      open_minutes: openMinutes,
      close_hour: closeHour,
      close_minutes: closeMinutes,
      closed_all_day: closedAllDay,
      open_all_day: openAllDay,
      has_lunch_break: hasLunchBreak,
      lunch_start_hour: lunchStartHour,
      lunch_start_minutes: lunchStartMinutes,
      lunch_end_hour: lunchEndHour,
      lunch_end_minutes: lunchEndMinutes,
    } = slot;
    const from = closedAllDay ? '' : getTime(openHour, openMinutes);
    const to = closedAllDay ? '' : getTime(closeHour, closeMinutes);
    const lunchFrom =
      hasLunchBreak && lunchStartHour != null
        ? getTime(lunchStartHour, lunchStartMinutes ?? 0)
        : '';
    const lunchTo =
      hasLunchBreak && lunchEndHour != null
        ? getTime(lunchEndHour, lunchEndMinutes ?? 0)
        : '';

    return {
      day,
      from,
      to,
      valid: !closedAllDay,
      openAllDay,
      hasLunchBreak: Boolean(hasLunchBreak),
      lunchFrom,
      lunchTo,
    };
  });
};

export const timeSlotTransform = timeSlots => {
  return timeSlots.map(slot => {
    const closed = slot.openAllDay ? false : !(slot.to && slot.from);
    const openAllDay = slot.openAllDay;
    let openHour = '';
    let openMinutes = '';
    let closeHour = '';
    let closeMinutes = '';

    if (!closed) {
      const fromDate = parse(slot.from, 'hh:mm a', new Date());
      const toDate = parse(slot.to, 'hh:mm a', new Date());
      openHour = getHours(fromDate);
      openMinutes = getMinutes(fromDate);
      closeHour = getHours(toDate);
      closeMinutes = getMinutes(toDate);
    }

    const hasLunchBreak = Boolean(slot.hasLunchBreak && slot.lunchFrom && slot.lunchTo);
    let lunchStartHour = null;
    let lunchStartMinutes = null;
    let lunchEndHour = null;
    let lunchEndMinutes = null;

    if (hasLunchBreak) {
      const lunchFromDate = parse(slot.lunchFrom, 'hh:mm a', new Date());
      const lunchToDate = parse(slot.lunchTo, 'hh:mm a', new Date());
      lunchStartHour = getHours(lunchFromDate);
      lunchStartMinutes = getMinutes(lunchFromDate);
      lunchEndHour = getHours(lunchToDate);
      lunchEndMinutes = getMinutes(lunchToDate);
    }

    return {
      day_of_week: slot.day,
      closed_all_day: closed,
      open_hour: openHour,
      open_minutes: openMinutes,
      close_hour: closeHour,
      close_minutes: closeMinutes,
      open_all_day: openAllDay,
      has_lunch_break: hasLunchBreak,
      lunch_start_hour: lunchStartHour,
      lunch_start_minutes: lunchStartMinutes,
      lunch_end_hour: lunchEndHour,
      lunch_end_minutes: lunchEndMinutes,
    };
  });
};

export const timeZoneOptions = () => {
  return Object.keys(timeZoneData).map(key => ({
    label: key,
    value: timeZoneData[key],
  }));
};
